stages:
- name: Build--api server image
  steps:
  - publishImageConfig:
      dockerfilePath: ./app/Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}/api-test:${CICD_GIT_COMMIT}
      #pushRemote: true
      #registry: 10.20.0.73:5443
    env:
      #PLUGIN_INSECURE: "true"
      #PLUGIN_MTU: "1000"
      PLUGIN_BUILD_ARGS: "--progress=tty --network=host"
      PLUGIN_MIRROR: "https://mirror.gcr.io"
      #PLUGIN_DEBUG: "true"
- name: deploy--API server
  steps:
  - applyYamlConfig:
      path: ./k8s-yaml/apitest-deployment.yaml
  - applyYamlConfig:
      path: ./k8s-yaml/apitest-service.yaml
  - applyYamlConfig:
      path: ./k8s-yaml/apitest-ingress.yaml

notification: {}
